### ISSUE TITLE
Share your theme with the Hugo community

### ISSUE THREAD

**Issue by digitalcraftsman** [adrianshort/tumble#1]
Hello @adrianshort,

just saw on Twitter that you started to develope a Hugo theme. All Hugo themes are usually listed in the [hugoThemes](https://github.com/gohugoio/hugoThemes/) repository. The list is used to  generate the website [themes.gohugo.io](http://themes.gohugo.io/) that allows users to browse all themes and watch a demo of them.

If you like to add your theme to the list follow the steps listed [here](https://github.com/gohugoio/hugoThemes/#adding-a-theme-to-the-list) and open an issue to let us know.

Cheers,
Digitalcraftsman

**Comment by adrianshort** [comment]
Hi @digitalcraftsman,

Thanks for the info. I'll be listing my theme on themes.gohugo.io when it reaches its first full release. Until then I assume you're looking for themes that are production ready rather than in pre-release development.

Cheers.

Adrian
